version: '3.8'

services:
  # API Service
  api:
    build:
      context: ./sheet_parser
    restart: always
    ports:
      - "5052:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - ONEDRIVE_CLIENT_ID=${ONEDRIVE_CLIENT_ID}
      - ONEDRIVE_TOKEN_PATH=/app/token_cache
    volumes:
      - sheet_parser_logs:/var/log/sheet_parser
      - onedrive_tokens:/app/token_cache
    command: gunicorn --bind 0.0.0.0:5000 --timeout 300 --workers 3 wsgi:app

  # Scheduled Import Service
  scheduler:
    build:
      context: ./sheet_parser
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - ONEDRIVE_FILE_ID=${ONEDRIVE_FILE_ID}
      - ONEDRIVE_CLIENT_ID=${ONEDRIVE_CLIENT_ID}
      - ONEDRIVE_TOKEN_PATH=/app/token_cache
      - DATABASE_URL=${DATABASE_URL}
      - IMPORT_MONTHS=2
      - LOG_FILE_PATH=/proc/1/fd/1
    volumes:
      - sheet_parser_logs:/var/log/sheet_parser
      - onedrive_tokens:/app/token_cache
    entrypoint: /bin/bash
    command: >
      -c "echo 'Scheduler container started. Running import script every 10 minutes.' &&
          while true; do
            echo '[SCHEDULER] Running scheduled import at $(date)'
            cd /app && python -m src.scheduled_import
            echo '[SCHEDULER] Waiting for next run...'
            sleep 600
          done"

volumes:
  sheet_parser_logs:
  onedrive_tokens: